### 함수

In [6]:
def add_sub(a,b):
    return a+b,a-b
x,y=add_sub(10,20) ###unpacking
print(x,y)

30 -10


In [31]:
 def print_numbers(*args):
        for arg in args:
            print (arg,end=" ")
print_numbers(1,2,3,4,5)
x=[10]
print_numbers(*x) ########## *이 unpacking 역할을 한다

1 2 3 4 5 10 

In [36]:
def personal_info(**kwargs):
    for key,value in kwargs.items():
        print (key,": ",value)
x={'name':'홍길동','age':30,'address':'서울시 용산구 이촌동'}
personal_info(**x) ###여기서도 **이 unpacking 역할을 한다

name :  홍길동
age :  30
address :  서울시 용산구 이촌동


In [50]:
def hello(count):
    if count == 0:    # 종료 조건을 만듦. count가 0이면 다시 hello 함수를 호출하지 않고 끝냄
        return
    else:
        print('Hello, world!', count)
    
        count -= 1      # count를 1 감소시킨 뒤
        hello(count)    # 다시 hello에 넣음
 
hello(5)    # hello 함수 호출


Hello, world! 5


In [56]:
factor=1
def factorial(n):
    global factor
    if n==1:
        print(factor)
    else:
        factor*=n
        n=n-1
        factorial(n)
factorial(5)

120


In [58]:
def factorial(n):
    if n==1:
        return 1
    return n* factorial(n-1)
print(factorial(5))

120


In [78]:
def pivonacci(n):
    if n==1:
        return 1
    if n==2:
        return 1
    return pivonacci(n-1)+pivonacci(n-2)
def pivonacci_array(n):
    arr=[]
    for i in range(1,n+1):
        arr.append(pivonacci(i))
    return arr
pivonacci_array(10)
        

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [85]:
plus_ten= lambda x: x+10
plus_ten(1)

11

In [87]:
list(map(lambda x:x+10,[1,2,3]))

[11, 12, 13]

In [90]:
###lambda 표현식에 조건문을 쓸때는 else를 꼭 써주어야한다. 
a=[1,2,3,4,5,6,7,8,9,10]
list(map(lambda x: str(x) if x==1 else float (x) if x==2 else x+10,a))

['1', 2.0, 13, 14, 15, 16, 17, 18, 19, 20]

In [96]:
a=[8,3,2,10,15,7,1,9,0,11]
list(filter(lambda x: x>5 and x<10,a))

[8, 7, 9]

In [113]:
x=10
def foo():
    global x
    x=20
    print(x)
foo()
print(x)

20
20


In [114]:
def print_hello():
    hello='Hellow, world!'
    def print_message():
        print(hello)
    print_message()
print_hello()

Hellow, world!


In [129]:
def A():
    x=10
    y=100
    def B():
        x=20
        def C():
            nonlocal x ###가장 가까운 x 가져오기
            nonlocal y 
            x=x+30
            y=y+300
            print(x)
            print(y)
        C()
    B()
A()

50
400


In [134]:
def calc():
    a=3
    b=5
    def mul_add(x):
        return a*x+b
    return mul_add
a=calc() ###할당을 함으로써 return 값으로 함수가 생기고
a(2) ##############클로저 짱신기하네 

11

In [151]:
def calc():
    a=3
    b=5
    total=0
    def mul_add(x):
        nonlocal total
        total=total+a*x+b
        print(total)
    return mul_add
c=calc()
c(1)
c(2)
c(3)

8
19
33


In [157]:
class Person:
    def __init__(self,x):
        self.x=x
    def myprint(self):
        print (self.x)
a=Person(3)
a.myprint()


3


In [ ]:
###비공개 속성이용하기
class Person:
    def __init__(self,name,age,address,wallet):
        self.name=name
        self.age=age
        self.address=address
        self.__wallet=wallet
    def pay(self,amount):
        self.__wallet-=amount
        print('이제 {0}원 남았네요.'.format(self.__wallet))
maria

In [ ]:
print('dasdasd%s')

In [43]:
class Person:
    count=0 
    def __init__(self):
        Person.count+=1
    @classmethod
    def print_count(self):
        print('{0}명 생성되었습니다'.format(cls.count))
james=Person()
maria=Person()
Person.print_count()

2명 생성되었습니다


In [44]:
Person.print_count(james)

2명 생성되었습니다


In [52]:
class Calc:
    @staticmethod
    def add(a, b):
        print(a + b)
 
    @staticmethod
    def mul(a, b):
        print(a * b)

In [53]:
a=Calc()
a.add(3,4)

7


## 코딩도장

### 넥슨 입사문제

어떤 자연수 n이 있을 때, d(n)을 n의 각 자릿수 숫자들과 n 자신을 더한 숫자라고 정의하자.

예를 들어

d(91) = 9 + 1 + 91 = 101

이 때, n을 d(n)의 제네레이터(generator)라고 한다. 위의 예에서 91은 101의 제네레이터이다.

어떤 숫자들은 하나 이상의 제네레이터를 가지고 있는데, 101의 제네레이터는 91 뿐 아니라 100도 있다. 그런데 반대로, 제네레이터가 없는 숫자들도 있으며, 이런 숫자를 인도의 수학자 Kaprekar가 셀프 넘버(self-number)라 이름 붙였다. 예를 들어 1,3,5,7,9,20,31 은 셀프 넘버 들이다.

1 이상이고 5000 보다 작은 모든 셀프 넘버들의 합을 구하라

In [23]:
def generator(n):
    n=str(n)
    sums=0
    for i in n:
        sums+=int(i)
    sums+=int(n)
    return sums
def self_number(n):
    gens=[]
    self_number=[]
    for i in range(1,n+1):
        gens.append(generator(i))
    for j in range(1,n+1):
        if j not in gens:
            self_number.append(j)
    
    return sum(self_number)
        

In [24]:
self_number(5000)

1227365

#### Spiral Array

문제는 다음과 같다:
"""
6 6

  0   1   2   3   4   5
 19  20  21  22  23   6
 18  31  32  33  24   7
 17  30  35  34  25   8
 16  29  28  27  26   9
 15  14  13  12  11  10
 """
위처럼 6 6이라는 입력을 주면 6 X 6 매트릭스에 나선형 회전을 한 값을 출력해야 한다.

In [24]:
import numpy as np

In [25]:
def spiral_array():
    ROW,COL=list(map(int,input().split()))
    MATRIX=[[-1 for i in range(COL)]for j in range(ROW)]
    x=0
    y=0
    dx=1
    dy=0
    count=0
    while count<=ROW*COL-2:
        if dx==1 and dy==0:
            while x<COL-1 and MATRIX[y+dy][x+dx]==-1 :
                MATRIX[y][x]=count
                count=count+1
                x+=dx
                y+=dy
            
            dx=0
            dy=1
            
        if dx==0 and dy==1:
             while y<ROW-1 and MATRIX[y+dy][x+dx]==-1 :
                MATRIX[y][x]=count
                count=count+1
                x+=dx
                y+=dy
             
             dx=-1
             dy=0
             
        if dx==-1 and dy==0:
             while x>0 and MATRIX[y+dy][x+dx]==-1 :
                MATRIX[y][x]=count
                count=count+1
                x+=dx
                y+=dy
             
             dx=0
             dy=-1
             
        if dx==0 and dy==-1:
             while y>0 and MATRIX[y+dy][x+dx]==-1 :
                MATRIX[y][x]=count
                count=count+1
                x+=dx
                y+=dy
             
             dx=1
             dy=0
    for i in range(len(MATRIX)):
        for j in range(len(MATRIX[i])):
            if MATRIX[i][j]==-1:
                MATRIX[i][j]=ROW*COL-1
                
                
    
    return np.array(MATRIX)
    

    
        
        
        
    

In [28]:
print(spiral_array())

10 10
[[ 0  1  2  3  4  5  6  7  8  9]
 [35 36 37 38 39 40 41 42 43 10]
 [34 63 64 65 66 67 68 69 44 11]
 [33 62 83 84 85 86 87 70 45 12]
 [32 61 82 95 96 97 88 71 46 13]
 [31 60 81 94 99 98 89 72 47 14]
 [30 59 80 93 92 91 90 73 48 15]
 [29 58 79 78 77 76 75 74 49 16]
 [28 57 56 55 54 53 52 51 50 17]
 [27 26 25 24 23 22 21 20 19 18]]
