In [14]:
import numpy as np

In [98]:
a=[[1,2,3],[4,5,6]]
a=np.array(a)
a[[0,1],[1,2]]

array([2, 6])

In [60]:
 np.random.rand(1,2)

array([[0.94350247, 0.09054416]])

In [63]:
np.arange(10,100,10).reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
dataframe

In [82]:
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [90]:
a[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [96]:
import pandas as pd
s1=pd.Series()
s1

Series([], dtype: float64)

In [97]:
pd.date_range('2019-09-01',periods=4)

DatetimeIndex(['2019-09-01', '2019-09-02', '2019-09-03', '2019-09-04'], dtype='datetime64[ns]', freq='D')

In [ ]:
pd.DataFrame(table_)

In [ ]:
table_data3={'봄':[]}