영상속성

In [1]:
import numpy as np
import cv2 as cv
import pandas as pd
path='C:/Users/edu/Desktop/OpenCV_data/OpenCV_data/'

In [2]:
img=cv.imread(path+'data/lena.jpg')

In [3]:
print(img.ndim,img.shape,img.dtype)
img

3 (512, 512, 3) uint8


array([[[128, 138, 225],
        [127, 137, 224],
        [126, 136, 224],
        ...,
        [126, 145, 236],
        [110, 129, 220],
        [ 86, 104, 197]],

       [[127, 137, 224],
        [127, 137, 224],
        [127, 137, 224],
        ...,
        [130, 150, 235],
        [112, 132, 217],
        [ 83, 102, 189]],

       [[127, 137, 224],
        [127, 137, 224],
        [128, 138, 225],
        ...,
        [127, 148, 230],
        [112, 133, 215],
        [ 85, 105, 190]],

       ...,

       [[ 55,  21,  82],
        [ 54,  20,  81],
        [ 62,  28,  92],
        ...,
        [ 82,  71, 175],
        [ 78,  68, 175],
        [ 74,  65, 175]],

       [[ 55,  18,  80],
        [ 56,  19,  81],
        [ 66,  32,  96],
        ...,
        [ 82,  69, 177],
        [ 80,  71, 181],
        [ 81,  72, 183]],

       [[ 56,  19,  81],
        [ 58,  21,  83],
        [ 68,  34,  98],
        ...,
        [ 81,  68, 176],
        [ 81,  72, 183],
        [ 84,  74, 188]]

In [4]:
img=np.int32(img)

In [5]:
print(img.dtype)

int32


In [6]:
img=np.uint8(img)
print(img.dtype)

uint8


In [7]:
img=img.astype(np.int32)
img.dtype

dtype('int32')

In [8]:
img.strides

(6144, 12, 4)

In [9]:
img=cv.imread(path+'data/lena.jpg',0)
print(img.shape)
img=img.flatten()
print(img.shape)
img=img.reshape(-1,512,512)
print(img.shape)
cv.imshow('img',img[0])
cv.waitKey()
cv.destroyAllWindows()
###-1은 알아서해라

(512, 512)
(262144,)
(1, 512, 512)


In [10]:
img=cv.imread(path+'data/lena.jpg',0)
img[200,100]=0
print(img[200:210,100:110])
img[200:300,100:400]=0
cv.imshow('img',img)
cv.waitKey()
cv.destroyAllWindows()

[[  0  98  98  95  99  95  97 102 104 106]
 [ 96  97  99  98  96  93  94  98 100 102]
 [ 96  96  99 100 101  98  99 102 104 105]
 [ 97  96  99  99 100  97  99 102 103 104]
 [ 95  95  98 100  99  96  98 101 102 103]
 [ 93  94  99 100 101  98 100 103 104 105]
 [ 96  97  99  98 100  98 100 103 103 104]
 [101 100  98  94 103 101 103 106 105 106]
 [102 108 101 100  99  99  98 106 102 104]
 [ 99 104  99  99  99 100 101 106 104 104]]


In [13]:
img=cv.imread(path+'data/lena.jpg')
img[100,200]=[255,0,0]
print(img[100,200:210])
img[100:400,200:300]=[255,0,0]
cv.imshow('img',img)
cv.waitKey()
cv.destroyAllWindows()

[[255   0   0]
 [116 115 207]
 [120 116 211]
 [107 103 198]
 [119 121 209]
 [116 118 206]
 [115 114 206]
 [112 111 203]
 [104 105 195]
 [110 112 200]]


In [19]:
img=cv.imread(path+'data/lena.jpg')
img[100:400,200:300]=[255,0,0]
img[100:400,300:400]=[255,255,255]
img[100:400,400:500]=[0,0,255]
cv.imshow('img',img)
cv.waitKey()
cv.destroyAllWindows()

In [22]:
%run ../OpenCV_Python/0214.py

start capture ...


<Figure size 640x480 with 1 Axes>

finish capture.


In [27]:
import cv2
import numpy as np
src=cv2.imread(path+'data/lena.jpg',cv2.IMREAD_GRAYSCALE)
dst=np.zeros_like(src)
N=4
height,width=src.shape
mean_value=src[:int(height/N),:int(width/N)].mean()
dst[:int(height/N),:int(width/N)]=mean_value
src[:int(height/N),:int(width/N)]=mean_value
cv.imshow('src',src)
cv.waitKey()
cv2.destroyAllWindows()

In [29]:
# 0406.py
import cv2
import numpy as np

src = cv2.imread(path+'data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=src.dtype)

N = 4 # 8, 32, 64
height, width = src.shape    # 그레이스케일 영상
##height, width,_ = src.shape # 컬러영상

h = height // N
w = width  // N
for i in range(N):
    for j in range(N):
        y = i*h
        x = j*w       
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w] = cv2.mean(roi)[0]   # 그레이스케일 영상
##        dst[y:y+h, x:x+w] = cv2.mean(roi)[0:3] # 컬러영상
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()


In [2]:
# 0407.py
import cv2
 
src = cv2.imread( path+'data/lena.jpg',cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)
print('roi =', roi)

img = src[roi[1]:roi[1]+roi[3],
            roi[0]:roi[0]+roi[2]]

cv2.waitKey()
cv2.destroyAllWindows()


roi = (17, 65, 224, 255)


In [8]:
# 0408.py
import cv2
 
src = cv2.imread(path+'data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, True, False)
print('rects =', rects)
for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), 255)    
##    img = src[r[1]:r[1]+r[3], r[0]:r[0]+r[2]]
##    cv2.imshow('Img', img)
##    cv2.waitKey()
cv2.imshow('src',src)
cv2.waitKey()    
cv2.destroyAllWindows()


rects = [[163 215 129 238]
 [ 91  12 279 375]
 [270 231 155 222]]


In [39]:
src = cv2.imread(path+'data/lena.jpg', cv2.IMREAD_GRAYSCALE)
shape=src.shape[0],src.shape[1],3
dst=np.zeros([512,512,3],dtype=np.uint8)
dst[:,:,0]=src
dst[100:400,200:300]=[255,255,255]
cv2.imshow('이병욱',src)
cv2.imshow('dst',dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [42]:
src = cv2.imread(path+'data/lena.jpg')
dst=cv2.split(src)
type(dst)
type(dst[0])
cv2.imshow('blue',dst[0])
cv2.imshow('green',dst[1])
cv2.imshow('red',dst[2])
cv2.waitKey()
cv2.destroyAllWindows()

In [43]:
src = cv2.imread(path+'data/lena.jpg')
b,g,r=cv2.split(src)
img=cv2.merge([b,g,r])
cv2.imshow('img',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [88]:
# 0413.py
import cv2
src = cv2.imread(path+'data/lena.jpg')

gray   = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
yCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv    = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
src2= cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)
cv2.imshow('gray',  gray)
cv2.imshow('yCrCv', yCrCv)
cv2.imshow('hsv',   hsv)
cv2.imshow('src',src2)
cv2.waitKey()    
cv2.destroyAllWindows()



In [58]:
print(gray.shape)
print(yCrCv.shape)
print(hsv.shape)

(512, 512)
(512, 512, 3)
(512, 512, 3)


In [104]:
# 0414.py
import cv2
import numpy as np
src = cv2.imread(path+'data/lena.jpg', cv2.IMREAD_GRAYSCALE)

dst = cv2.resize(src, dsize=(320, 240))
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.2)
cv2.imshow('src',img)
cv2.imshow('dst', dst)
cv2.imshow('dst2', dst2)
cv2.waitKey()    
cv2.destroyAllWindows()



In [101]:
# 0416.py
import cv2
src = cv2.imread(path+'data/lena.jpg')

rows, cols, channels = src.shape
M1 = cv2.getRotationMatrix2D( (rows/2, cols/2),  45, 0.5 )
M2 = cv2.getRotationMatrix2D( (rows/2, cols/2), -45, 1.0 )

dst1 = cv2.warpAffine( src, M1, (rows, cols))
dst2 = cv2.warpAffine( src, M2, (rows, cols))

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()


In [113]:
# 0417.py
import cv2
import numpy as np

src1 = cv2.imread(path+'data/lena.jpg', cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape=(512,512), dtype=np.uint8) + 100

dst1 = src1 + src2
dst2=cv2.add(src1, src2)
#dst2 = cv2.add(src1, src2, dtype = cv2.CV_8U)

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()


In [122]:
# 0418.py: OpenCV-Python Tutorials 참조
import cv2
import numpy as np

src1 = cv2.imread(path+'data/lena.jpg')
src2 = cv2.imread(path+'data/opencv_logo.png')
cv2.imshow('src2',  src2)

#1
rows,cols,channels = src2.shape
roi = src1[0:rows, 0:cols]

#2
gray = cv2.cvtColor(src2,cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(gray, 160, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)
cv2.imshow('mask',  mask)
cv2.imshow('mask_inv',  mask_inv)

#3
src1_bg = cv2.bitwise_and(roi, roi, mask = mask)
cv2.imshow('src1_bg',  src1_bg)

#4
src2_fg = cv2.bitwise_and(src2, src2, mask = mask_inv)
cv2.imshow('src2_fg',  src2_fg)

#5
##dst = cv2.add(src1_bg, src2_fg)
dst = cv2.bitwise_or(src1_bg, src2_fg)
cv2.imshow('dst',  dst)

#6
src1[0:rows, 0:cols] = dst

cv2.imshow('result',src1)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [118]:
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()